version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/card-website

hooks:
  AfterInstall:
    - location: scripts/make_executable.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
